name: 'Terraform PR Commenter'
description: 'Adds opinionated comments to a PR from Terraform plan'
author: '@andresb39'
branding:
  icon: 'git-pull-request'
  color: 'purple'
runs:
  using: 'docker'
  image: 'Dockerfile'
